kind: Deployment
apiVersion: apps/v1
metadata:
  name: blue
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: blue
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue
#EXISTS
#NOTIN
#prefferedDuringSchedulingIgnoredDuringExecution:
