kind: Pod
apiVersion: v1
metadata:
  name: "soban"
spec:
  serviceAccountName: dasboard-sa
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "2000"]
    securityContext:
      runAsUser: 1000
      #capabilities must be at pod level
      capabilities:
        add: ["Mac_admin"]
