# kind: PersistantVolume
# apiVersion: v1
# metadata:
#   name: pv1
#   lables:
#     type: low
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   awsElasticBlockStore:
#     volumeId: "id"
#     fsType: ex4
# SECOND WAY
kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-volume
spec: 
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  capacity:
          
    storage: 1Gi
  hostPath:
    path: /opt/volume/ngix