# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: log-volume
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
  
#   storageClassName: manual

#   hostPath:
#     path: /opt/volume/nginx

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: log-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 200Mi
#   storageClassName: manual
# apiVersion: v1
# kind: Pod
# metadata:
#   name: logger 
# spec:
#   volumes:
#   - name: vol
#     persistatVolumeClaim:
#       claimName: log-claim
#   containers:
#   - name: nginx
#     image: nginx:alpine
#     volumeMounts:
#     - name: vol
#       mountPath: /var/www/nginx

kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /drupal-data