kind: Pod
apiVersion: v1
metadata:
  name: webapp
spec:
  containers:
  - name: nginx
    image: kodekloud/event-simulator
    volumeMounts:
    - mountPath:  /log
      name: log-volume
  volumes:
  - name: log-volume
    
    hostPath:
      path:  /var/log/webapp
      type: Directory