kind: CronJob
apiVersion: batch/v1
metadata:
  name: Jjob1
spec:
  schedule: "* * * * *"
  JobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        metadata:
          labels:
            ap:te
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
          restartPolicy: never